version: '3'

services:
  aria2:
    image: centos
    restart: always
    volumes:
      - "./aria2:/etc/aria2"
      - "./store:/store"
      - "./scripts/aria2.sh:/aria2.sh"
    command: bash /aria2.sh

  php:
    image: php:fpm
    volumes:
        - "./store:/usr/share/nginx/html/store"
        - "./scripts/php.sh:/php.sh"
    command: bash /php.sh

  nginx:
    image: nginx
    restart: always
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/index.html:/usr/share/nginx/html/index.html"
      - "./store:/usr/share/nginx/html/store"
      - "./scripts/nginx.sh:/nginx.sh"
    ports:
      - "9099:80"
    links:
      - aria2
      - php
    depends_on:
      - aria2
      - php
    command: bash /nginx.sh