version: '3'

services:
  aria2:
    image: centos:7
    restart: always
    volumes:
      - "./aria2:/etc/aria2"
      - "./store:/store"
      - "./scripts/aria2.sh:/aria2.sh"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "1m"
    command: bash /aria2.sh

  php:
    image: php:fpm
    volumes:
        - "./store:/usr/share/nginx/html/store"
        - "./scripts/php.sh:/php.sh"
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "1m"
    command: bash /php.sh

  nginx:
    image: nginx
    restart: always
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/index.html:/usr/share/nginx/html/index.html"
      - "./store:/usr/share/nginx/html/store"
      - "./scripts/nginx.sh:/nginx.sh"
    ports:
      - "9099:80"
    links:
      - aria2
      - php
    depends_on:
      - aria2
      - php
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "1m"
    command: bash /nginx.sh
